In [2]:
# dependencies
import pandas as pd


# file path
provisional_stats = 'Provisional_COVID-19_Death_Counts_by_Sex__Age__and_State.csv'

#read the data file
ps_df = pd.read_csv(provisional_stats)

# drop unneeded columns
ps_df = ps_df.drop(columns=['Data as of', 'Start Date', 'End Date', 'Footnote'])

#print df header
ps_df.head()

,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
0,United States,All Sexes,All Ages,"347,131","3,329,907","331,354","161,474","8,726","524,629"
1,United States,All Sexes,Under 1 year,39,"18,436",193,6,21,247
2,United States,All Sexes,0-17 years,165,"32,453",536,29,175,847
3,United States,All Sexes,1-4 years,21,"3,388",120,3,59,197
4,United States,All Sexes,5-14 years,58,"5,440",153,11,74,274

In [3]:
# group total stats based on state totals
# obtain state total rows
ps_df_filtered = ps_df[ps_df['Sex']=='All Sexes']
# drilling to state totals
ps_df_filtered = ps_df_filtered[ps_df_filtered['Age group'] == 'All Ages']
# dropping US Totals row
indexname= ps_df_filtered[ps_df_filtered['State']=='United States'].index
ps_df_filtered.drop(indexname, inplace =True)
# removing remaining unneeded columns
ps_df_filtered = ps_df_filtered.drop(columns=['Sex', 'Age group'])
#replace NaN with 0
ps_df_filtered = ps_df_filtered.fillna(0)
# reset index
ps_df_filtered = ps_df_filtered.reset_index(drop=True)
# view new head
ps_df_filtered.head()
# check # of rows
len(ps_df_filtered)

53

In [4]:
#save cleaned csv for later merge
ps_df_filtered.to_csv("Cleaned_Data/Cleaned_Provisional_Stats.csv", index=False)

In [5]:
# open next CSV file for merge with cleaned file
popden = 'Population_Density.csv'
# read csv
population_density = pd.read_csv(popden)
#print head
population_density.head()
# check # of rows
#len(population_density)

           State    Density      Pop  LandArea
0     New Jersey  1206.7609  8874520      7354
1   Rhode Island  1026.6054  1061510      1034
2  Massachusetts   886.1846  6912240      7800
3    Connecticut   733.7505  3552820      4842
4       Maryland   624.8522  6065440      9707

In [6]:
#merge df merge how right to drop NYC and Puerto Rico due to no density info
stats_popden_merge = pd.merge(ps_df_filtered, population_density, on='State', how ='right')
# display new df header
stats_popden_merge.head()

,State,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Density,Pop,LandArea
0,Alabama,"6,195","62,730","5,069","2,009",135,"9,381",97.4270,4934190,50645
1,Alaska,193,"4,721",270,109,0,363,1.2694,724357,570641
2,Arizona,"8,498","77,079","8,720","4,955",147,"12,409",66.2016,7520100,113594
3,Arkansas,"3,728","37,869","3,769","1,662",101,"5,931",58.3059,3033950,52035
4,California,"27,622","315,502","33,784","15,695",813,"46,518",254.2929,39613500,155779

In [7]:
# open next CSV file for merge with cleaned file
vacccsv = 'COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Pfizer.csv'
# read csv
vacc_dist = pd.read_csv(vacccsv)
#clean non alpha numeric characters from first column
vacc_dist['Jurisdiction'] = vacc_dist.Jurisdiction.str.replace(r'[^a-zA-Z ]\s?',r'',regex=True)
# rename Jurisdiction column State for merge
vacc_dist = vacc_dist.rename(columns={"Jurisdiction": "State"})
#print head
vacc_dist.head()
# check # of rows
#len(vacc_dist)

,State,HHS Region,Doses allocated week of 12/14,Second Dose Shipment (21 days later) week of 12/14,Doses allocated week of 12/21,Second Dose Shipment (21 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (21 days later) week of 12/28,Doses allocated for distribution week of 01/04,Second dose shipment for distribution (21 days later) week of 01/04,Doses allocated for distribution week of 01/10,Second dose shipment for distribution (21 days later) week of 01/10,Doses allocated for distribution week of 01/18,Second dose shipment for distribution (21 days later) week of 01/18,Doses allocated for distribution week of 01/25,Second dose shipment for distribution (21 days later) week of 01/25,"Total Pfizer Allocation ""First Dose"" Shipments","Total Allocation Pfizer ""Second Dose"" Shipments"
0,Connecticut,Region 1,"31,200","31,200","22,425","22,425","28,275","28,275","22,425","22,425","22,425","22,425","23,400","23,400","23,400","23,400","173,550","173,550"
1,Maine,Region 1,"12,675","12,675","8,775","8,775","10,725","10,725","8,775","8,775","8,775","8,775","8,775","8,775","8,775","8,775","67,275","67,275"
2,Massachusetts,Region 1,"59,475","59,475","42,900","42,900","54,600","54,600","42,900","42,900","42,900","42,900","43,875","43,875","43,875","43,875","330,525","330,525"
3,New Hampshire,Region 1,"12,675","12,675","8,775","8,775","10,725","10,725","8,775","8,775","8,775","8,775","8,775","8,775","8,775","8,775","67,275","67,275"
4,Rhode Island,Region 1,"9,750","9,750","6,825","6,825","8,775","8,775","6,825","6,825","6,825","6,825","6,825","6,825","6,825","6,825","52,650","52,650"

In [8]:
#merge df merge how right to drop NYC and Puerto Rico due to no density info
stats_popden_vaccdist_merge = pd.merge(stats_popden_merge, vacc_dist, on='State', how ='right')
#replace NaN with 0
stats_popden_vaccdist_merge = stats_popden_vaccdist_merge.fillna(0)
# removing remaining unneeded columns
stats_popden_vaccdist_merge = stats_popden_vaccdist_merge.drop(columns=['Doses allocated for distribution week of 01/04',
                                                                        'Doses allocated week of 12/14',
                                                                        'Second Dose Shipment (21 days later) week of 12/14',
                                                                        'Doses allocated week of 12/21',
                                                                        'Second Dose Shipment (21 days later) week of 12/21',
                                                                        'Doses allocated week of 12/28'
                                                                        'Second Dose Shipment (21 days later) week of 12/28',
                                                                        'Doses allocated week of 01/04'
                                                                        'Second dose shipment for distribution (21 days later) week of 01/04',
                                                                        'Doses allocated for distribution week of 01/10',
                                                                        'Second dose shipment for distribution (21 days later) week of 01/10',
                                                                        'Doses allocated for distribution week of 01/18',
                                                                        'Second dose shipment for distribution (21 days later) week of 01/18',
                                                                        'Doses allocated for distribution week of 01/25',
                                                                        'Second dose shipment for distribution (21 days later) week of 01/25',
                                                                        'HHS Region'])
# display new df header
stats_popden_vaccdist_merge.head()

,State,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Density,Pop,LandArea,Doses allocated week of 12/14,Second Dose Shipment (21 days later) week of 12/14,Doses allocated week of 12/21,Second Dose Shipment (21 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (21 days later) week of 12/28,"Total Pfizer Allocation ""First Dose"" Shipments","Total Allocation Pfizer ""Second Dose"" Shipments"
0,Alabama,"6,195","62,730","5,069","2,009",135,"9,381",97.4270,4934190.0,50645.0,"40,950","40,950","29,250","29,250","38,025","38,025","227,175","227,175"
1,Alaska,193,"4,721",270,109,0,363,1.2694,724357.0,570641.0,"35,100","35,100",0,0,0,0,"62,400","62,400"
2,Arizona,"8,498","77,079","8,720","4,955",147,"12,409",66.2016,7520100.0,113594.0,"58,500","58,500","41,925","41,925","53,625","53,625","323,700","323,700"
3,Arkansas,"3,728","37,869","3,769","1,662",101,"5,931",58.3059,3033950.0,52035.0,"25,350","25,350","18,525","18,525","23,400","23,400","141,375","141,375"
4,California,"27,622","315,502","33,784","15,695",813,"46,518",254.2929,39613500.0,155779.0,"327,600","327,600","233,025","233,025","297,375","297,375","1,806,675","1,806,675"

In [23]:
#save cleaned csv for later merge
stats_popden_vaccdist_merge.to_csv("Cleaned_Data/Combined_COVID_Den_Dist.csv", index=False)